# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Arvind SA
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Arvind S.A.
profile_img: assets/images/arvind.jpg
profile: 
social:
  facebook: http://www.facebook.com/arvindsa
  linkedin: https://www.linkedin.com/in/arvindsa90/ 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
